#!/usr/bin/env python3

# This is a simple wrapper that runs the computeEvidenceRatio code with the 
# required input parameters supplied by the submit.sh script.

import os
import sys
import argparse

from GWXtreme import eos_model_selection as ems


parser = argparse.ArgumentParser()
parser.add_argument("-i", "--input", action="store", help="Name of posterior file")
parser.add_argument("-N", "--nums", action="store", type=int, help="Number of trials")
parser.add_argument("-o", "--output", action="store", help="Name of output json file")
parser.add_argument("-T", "--target", action="store", help="Name of the target EoS")
parser.add_argument("-r", "--reference", action="store", help="Name of the reference EoS")
args = parser.parse_args()


modsel = ems.Model_selection(posteriorFile=args.input, priorFile=None)
x = modsel.computeEvidenceRatio(args.target, args.reference, trials=args.nums, save=args.output)

